/*
 */
package booknaviger.exceptioninterface;

import java.awt.Color;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Inervo
 */
public class LogInterface extends javax.swing.JDialog {
    
    private static LogInterface instance = null;
    StyledDocument doc = null;
    
    /**
     *
     * @return
     */
    public static LogInterface getInstance() {
        synchronized(LogInterface.class) {
            if (instance == null) {
                instance = new LogInterface();
            }
        }
        return instance;
    }

    /**
     * Creates new form LogInterface
     */
    private LogInterface() {
        initComponents();
        doc = logTextPane.getStyledDocument();
        Style newEntryStyle = logTextPane.addStyle("newEntry", null);
        StyleConstants.setForeground(newEntryStyle, Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logScrollPane = new javax.swing.JScrollPane();
        logTextPane = new javax.swing.JTextPane();

        setTitle("Error log");

        logScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        logScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        logScrollPane.setViewportView(logTextPane);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(logScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(logScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param newLog
     */
    protected synchronized void publishNewLog(String newLog) {
        logTextPane.setText(logTextPane.getText());
        try {
            doc.insertString(doc.getLength(), newLog + System.getProperty("line.separator"), logTextPane.getStyle("newEntry"));
        } catch (BadLocationException ex) {
            logTextPane.setText(newLog);
        }
        setVisible(true);
        requestFocus();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane logScrollPane;
    private javax.swing.JTextPane logTextPane;
    // End of variables declaration//GEN-END:variables
}
