/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ErrorBox.java
 *
 * Created on 17 mai 2010, 13:21:10
 */

package booknaviger.errorhandler;

import javax.swing.JTextArea;
import org.jdesktop.application.Action;

/**
 *
 * @author Inervo
 */
public class ErrorBox extends javax.swing.JDialog {

    /** Creates new form ErrorBox */
    public ErrorBox() {
        super((java.awt.Frame) null, true);
        initComponents();
        getRootPane().setDefaultButton(okButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        errorTextAreaScrollPane = new javax.swing.JScrollPane();
        errorTextArea = new javax.swing.JTextArea();
        copyButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(booknaviger.BookNavigerApp.class).getContext().getResourceMap(ErrorBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        LogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLabel.setIcon(resourceMap.getIcon("LogoLabel.icon")); // NOI18N
        LogoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LogoLabel.setName("LogoLabel"); // NOI18N

        infoLabel.setText(resourceMap.getString("infoLabel.text")); // NOI18N
        infoLabel.setName("infoLabel"); // NOI18N

        errorTextAreaScrollPane.setName("errorTextAreaScrollPane"); // NOI18N

        errorTextArea.setEditable(false);
        errorTextArea.setMargin(new java.awt.Insets(0, 10, 0, 10));
        errorTextArea.setName("errorTextArea"); // NOI18N
        errorTextAreaScrollPane.setViewportView(errorTextArea);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(booknaviger.BookNavigerApp.class).getContext().getActionMap(ErrorBox.class, this);
        copyButton.setAction(actionMap.get("copyErrorMessageToClipboard")); // NOI18N
        copyButton.setText(resourceMap.getString("copyButton.text")); // NOI18N
        copyButton.setToolTipText(resourceMap.getString("copyButton.toolTipText")); // NOI18N
        copyButton.setName("copyButton"); // NOI18N

        okButton.setAction(actionMap.get("quit")); // NOI18N
        okButton.setName("okButton"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(532, Short.MAX_VALUE)
                .add(copyButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(okButton)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(LogoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(infoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .add(4, 4, 4))
            .add(errorTextAreaScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(LogoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(infoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(errorTextAreaScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(copyButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Executer lorsque l'on quitte la fenetre
     */
    @Action
    public void quit() {
        setVisible(false);
        errorTextArea.setText(null);
        dispose();
    }

    /**
     * zone de texte
     * @return retourne la zone de texte
     */
    public JTextArea getErrorTextArea() {
        return errorTextArea;
    }

    /**
     * copie le contenu de la zone de texte dans le presse-papier
     */
    @Action
    public void copyErrorMessageToClipboard() {
        errorTextArea.selectAll();
        errorTextArea.copy();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JButton copyButton;
    private javax.swing.JTextArea errorTextArea;
    private javax.swing.JScrollPane errorTextAreaScrollPane;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
