/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package booknaviger.errorhandler;

import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 *
 * @author Inervo
 */
public class KnownErrorBox extends javax.swing.JDialog {

    public static final int ERROR_LOGO = 0;
    public static final int WARNING_lOGO = 1;
    public static final int INFO_LOGO = 2;

    private ResourceMap resourceMap = Application.getInstance(booknaviger.BookNavigerApp.class).getContext().getResourceMap(KnownErrorBox.class);

    /**
     * Constructeur de la fenêtre de sélection du mode
     * @param frame Frame parente
     * @param modal modalité de la fenêtre
     */
    public KnownErrorBox(java.awt.Frame frame, int gravity, String errorDescResourceString, Object... args) {
        super(frame, true);
        initComponents();
        getRootPane().setDefaultButton(okButton);
        this.setLocationRelativeTo(this.getParent());
        if (gravity == INFO_LOGO)
            logoLabel.setIcon(resourceMap.getIcon("Info_Logo.icon"));
        if (gravity == WARNING_lOGO)
            logoLabel.setIcon(resourceMap.getIcon("Warning_Logo.icon"));
        if (gravity == ERROR_LOGO)
            logoLabel.setIcon(resourceMap.getIcon("Error_Logo.icon"));
        infoLabel.setText("<html>" + resourceMap.getString(errorDescResourceString.concat(".string"), args) + "</html>");
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(booknaviger.BookNavigerApp.class).getContext().getResourceMap(KnownErrorBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setModal(true);
        setName("Form"); // NOI18N

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logoLabel.setName("logoLabel"); // NOI18N

        infoLabel.setName("infoLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(booknaviger.BookNavigerApp.class).getContext().getActionMap(KnownErrorBox.class, this);
        okButton.setAction(actionMap.get("quit")); // NOI18N
        okButton.setName("okButton"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .add(okButton)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(logoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(81, 81, 81)
                .add(infoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(logoLabel)
                    .add(infoLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 65, Short.MAX_VALUE)
                .add(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Executé lors de la sortie de la fenêtre
     */
    @Action
    public void quit() {
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
