/*
 */
package booknaviger;

import booknaviger.inet.InetBasics;
import booknaviger.macworld.MacOSXApplicationAdapter;
import booknaviger.picturehandler.AbstractImageHandler;
import booknaviger.picturehandler.FolderHandler;
import booknaviger.picturehandler.PdfHandler;
import booknaviger.picturehandler.RarHandler;
import booknaviger.picturehandler.ZipHandler;
import booknaviger.readinterface.ReadInterface;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileFilter;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Inervo
 */
public class MainInterface extends javax.swing.JFrame {
    
    private File booksDirectory = null;
    private Timer busyIconTimer;
    private int busyIconIndex = 0;
    private Icon idleIcon;
    private Icon[] busyIcons = new Icon[15];
    private boolean isAdjusting = false;
    private File serie = null;
    private File album = null;
    private PreviewImageLoader threadedPreviewLoader = new PreviewImageLoader();
    private AbstractImageHandler imageHandler = null;
    private ResourceBundle resourceBundle = java.util.ResourceBundle.getBundle("booknaviger/resources/MainInterface");
    private volatile ReadInterface readInterface = null;
    private static volatile MainInterface instance = null;

    public static MainInterface getInstance() {
        if (instance == null) {
            synchronized(MainInterface.class) {
                if (instance == null) {
                    instance = new MainInterface();
                }
            }
        }
        return instance;
    }
    
    /**
     * Creates new form MainInterface
     */
    private MainInterface() {
        macInit();
        initComponents();
        previewComponent.setStatusToolBarHeigh(statusToolBar.getHeight() + mainToolBar.getHeight());
        setTimer();
    }
    
    private void macInit() {
        if (MacOSXApplicationAdapter.isMac()) {
            new MacOSXApplicationAdapter();
        }
    }
    
    private static void preInterface() {
        if (MacOSXApplicationAdapter.isMac()) {
            MacOSXApplicationAdapter.setMacInterfaceAndCommands();
        }
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setTimer() {
        int busyAnimationRate = 30;
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = new javax.swing.ImageIcon(getClass().getResource(java.text.MessageFormat.format(resourceBundle.getString("busy_icon_{0}"), new Object[] {i})));
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = new javax.swing.ImageIcon(getClass().getResource(resourceBundle.getString("idle_icon")));
        statusAnimationLabel.setIcon(idleIcon);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languageButtonGroup = new javax.swing.ButtonGroup();
        booksFolderFileChooser = new javax.swing.JFileChooser();
        aboutDialog = new javax.swing.JDialog(this);
        closeAboutDialogButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        appTitleLabel = new javax.swing.JLabel();
        appDescLabel = new javax.swing.JLabel();
        productVersionLabel = new javax.swing.JLabel();
        vendorLabel = new javax.swing.JLabel();
        homepageLabel = new javax.swing.JLabel();
        appVersionLabel = new javax.swing.JLabel();
        appVendorLabel = new javax.swing.JLabel();
        appHomepageLabel = new javax.swing.JLabel();
        mainToolBar = new javax.swing.JToolBar();
        resumeButton = new javax.swing.JButton();
        toolbarSeparator1 = new javax.swing.JToolBar.Separator();
        refreshAllButton = new javax.swing.JButton();
        refreshCurrentButton = new javax.swing.JButton();
        toolbarSeparator2 = new javax.swing.JToolBar.Separator();
        profileComboBox = new javax.swing.JComboBox();
        booksPreviewSplitPane = new javax.swing.JSplitPane();
        seriesScrollPane = new javax.swing.JScrollPane();
        seriesTable = new javax.swing.JTable();
        albumsScrollPane = new javax.swing.JScrollPane();
        albumsTable = new javax.swing.JTable();
        previewComponent = new booknaviger.PreviewComponent();
        statusToolBar = new javax.swing.JToolBar();
        statusToolBarFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        statusAnimationLabel = new javax.swing.JLabel();
        toolBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        generateReportMenuItem = new javax.swing.JMenuItem();
        bookFolderMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        optionMenu = new javax.swing.JMenu();
        resumeMenuItem = new javax.swing.JMenuItem();
        profileMenu = new javax.swing.JMenu();
        profilesMenuItem = new javax.swing.JMenuItem();
        profileSeparator = new javax.swing.JPopupMenu.Separator();
        optionsSeparator = new javax.swing.JPopupMenu.Separator();
        refreshAllMenuItem = new javax.swing.JMenuItem();
        refreshCurrentMenuItem = new javax.swing.JMenuItem();
        languageMenu = new javax.swing.JMenu();
        defaultLanguageCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        languageSeparator = new javax.swing.JPopupMenu.Separator();
        englishLanguageCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        frenchLanguageCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        helpMenu = new javax.swing.JMenu();
        autoUpdatesCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        booksFolderFileChooser.setDialogTitle(resourceBundle.getString("books-folder_title_jdialog")); // NOI18N
        booksFolderFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        aboutDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        closeAboutDialogButton.setText("Close");
        closeAboutDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAboutBox(evt);
            }
        });

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/about.png"))); // NOI18N

        appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("booknaviger/resources/Application"); // NOI18N
        appTitleLabel.setText(bundle.getString("appTitle")); // NOI18N

        appDescLabel.setText(bundle.getString("appDesc")); // NOI18N

        productVersionLabel.setFont(productVersionLabel.getFont().deriveFont(productVersionLabel.getFont().getStyle() | java.awt.Font.BOLD));
        productVersionLabel.setText(bundle.getString("productVersion")); // NOI18N

        vendorLabel.setFont(vendorLabel.getFont().deriveFont(vendorLabel.getFont().getStyle() | java.awt.Font.BOLD));
        vendorLabel.setText(bundle.getString("vendor")); // NOI18N

        homepageLabel.setFont(homepageLabel.getFont().deriveFont(homepageLabel.getFont().getStyle() | java.awt.Font.BOLD));
        homepageLabel.setText(bundle.getString("homepage")); // NOI18N

        appVersionLabel.setText(bundle.getString("appVersion")); // NOI18N

        appVendorLabel.setText(bundle.getString("appVendor")); // NOI18N

        appHomepageLabel.setText(bundle.getString("appHomepage")); // NOI18N
        appHomepageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homepageLabelMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout aboutDialogLayout = new org.jdesktop.layout.GroupLayout(aboutDialog.getContentPane());
        aboutDialog.getContentPane().setLayout(aboutDialogLayout);
        aboutDialogLayout.setHorizontalGroup(
            aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(aboutDialogLayout.createSequentialGroup()
                .add(imageLabel)
                .add(aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(aboutDialogLayout.createSequentialGroup()
                        .add(38, 38, 38)
                        .add(aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(appTitleLabel)
                            .add(appDescLabel)
                            .add(aboutDialogLayout.createSequentialGroup()
                                .add(aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(productVersionLabel)
                                    .add(vendorLabel)
                                    .add(homepageLabel))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(appHomepageLabel)
                                    .add(appVersionLabel)
                                    .add(appVendorLabel)))))
                    .add(aboutDialogLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(closeAboutDialogButton)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        aboutDialogLayout.setVerticalGroup(
            aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .add(appTitleLabel)
                .add(18, 18, 18)
                .add(appDescLabel)
                .add(18, 18, 18)
                .add(aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(aboutDialogLayout.createSequentialGroup()
                        .add(appVersionLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(vendorLabel)
                            .add(appVendorLabel)))
                    .add(productVersionLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(appHomepageLabel)
                    .add(homepageLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(closeAboutDialogButton)
                .addContainerGap())
            .add(imageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BookNaviger"); // NOI18N

        mainToolBar.setFloatable(false);
        mainToolBar.setRollover(true);
        mainToolBar.setPreferredSize(new java.awt.Dimension(166, 25));

        resumeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/resume.png"))); // NOI18N
        resumeButton.setFocusable(false);
        resumeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resumeButton.setMaximumSize(new java.awt.Dimension(20, 20));
        resumeButton.setMinimumSize(new java.awt.Dimension(20, 20));
        resumeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(resumeButton);
        mainToolBar.add(toolbarSeparator1);

        refreshAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/refreshSeries.png"))); // NOI18N
        refreshAllButton.setFocusable(false);
        refreshAllButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshAllButton.setMaximumSize(new java.awt.Dimension(20, 20));
        refreshAllButton.setMinimumSize(new java.awt.Dimension(20, 20));
        refreshAllButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAllActionPerformed(evt);
            }
        });
        mainToolBar.add(refreshAllButton);

        refreshCurrentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/refreshAlbums.png"))); // NOI18N
        refreshCurrentButton.setFocusable(false);
        refreshCurrentButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshCurrentButton.setMaximumSize(new java.awt.Dimension(20, 20));
        refreshCurrentButton.setMinimumSize(new java.awt.Dimension(20, 20));
        refreshCurrentButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshCurrentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCurrentAlbumActionPerformed(evt);
            }
        });
        mainToolBar.add(refreshCurrentButton);
        mainToolBar.add(toolbarSeparator2);

        profileComboBox.setMaximumSize(new java.awt.Dimension(200, 20));
        profileComboBox.setMinimumSize(new java.awt.Dimension(96, 20));
        mainToolBar.add(profileComboBox);

        getContentPane().add(mainToolBar, java.awt.BorderLayout.PAGE_START);

        booksPreviewSplitPane.setDividerLocation(280);
        booksPreviewSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        booksPreviewSplitPane.setMinimumSize(new java.awt.Dimension(400, 400));
        booksPreviewSplitPane.setPreferredSize(new java.awt.Dimension(458, 400));

        seriesScrollPane.setMinimumSize(new java.awt.Dimension(400, 200));

        seriesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Series", "Nb"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        seriesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        seriesTable.setShowVerticalLines(false);
        seriesTable.getTableHeader().setReorderingAllowed(false);
        seriesTable.getColumnModel().getColumn(0).setHeaderValue(resourceBundle.getString("seriesTable.title"));
        seriesTable.getColumnModel().getColumn(1).setMaxWidth(50);
        seriesTable.getColumnModel().getColumn(1).setMinWidth(25);
        seriesScrollPane.setViewportView(seriesTable);
        ListSelectionModel seriesListSelectionModel = seriesTable.getSelectionModel();
        seriesListSelectionModel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                seriesTableValueChanged(evt);
            }
        });

        booksPreviewSplitPane.setTopComponent(seriesScrollPane);

        albumsScrollPane.setMinimumSize(new java.awt.Dimension(400, 100));

        albumsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Album", "Extension"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        albumsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        albumsTable.setShowHorizontalLines(false);
        albumsTable.setShowVerticalLines(false);
        albumsTable.getTableHeader().setReorderingAllowed(false);
        albumsTable.getColumnModel().getColumn(1).setMinWidth(0);
        albumsTable.getColumnModel().getColumn(1).setMaxWidth(0);
        albumsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                albumsTableMouseClicked(evt);
            }
        });
        albumsScrollPane.setViewportView(albumsTable);
        ListSelectionModel albumsListSelectionModel = albumsTable.getSelectionModel();
        albumsListSelectionModel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                albumsTableValueChanged(evt);
            }
        });

        booksPreviewSplitPane.setRightComponent(albumsScrollPane);

        getContentPane().add(booksPreviewSplitPane, java.awt.BorderLayout.CENTER);

        previewComponent.setDoubleBuffered(true);
        previewComponent.setMinimumSize(new java.awt.Dimension(100, 400));
        previewComponent.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                previewComponentComponentResized(evt);
            }
        });

        org.jdesktop.layout.GroupLayout previewComponentLayout = new org.jdesktop.layout.GroupLayout(previewComponent);
        previewComponent.setLayout(previewComponentLayout);
        previewComponentLayout.setHorizontalGroup(
            previewComponentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 236, Short.MAX_VALUE)
        );
        previewComponentLayout.setVerticalGroup(
            previewComponentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(previewComponent, java.awt.BorderLayout.EAST);

        statusToolBar.setFloatable(false);
        statusToolBar.setRollover(true);
        statusToolBar.setPreferredSize(new java.awt.Dimension(166, 25));
        statusToolBar.add(statusToolBarFiller);

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statusToolBar.add(statusAnimationLabel);

        getContentPane().add(statusToolBar, java.awt.BorderLayout.PAGE_END);

        fileMenu.setMnemonic('f');
        fileMenu.setText(resourceBundle.getString("file_menu")); // NOI18N

        generateReportMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/report.png"))); // NOI18N
        generateReportMenuItem.setText(resourceBundle.getString("report-generate_menu")); // NOI18N
        fileMenu.add(generateReportMenuItem);

        bookFolderMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/library.png"))); // NOI18N
        bookFolderMenuItem.setText(resourceBundle.getString("books-folder_menu")); // NOI18N
        bookFolderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFolderMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(bookFolderMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/quit.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText(resourceBundle.getString("exit_menu")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        toolBar.add(fileMenu);

        optionMenu.setText(resourceBundle.getString("controls_menu")); // NOI18N

        resumeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/resume.png"))); // NOI18N
        resumeMenuItem.setText(resourceBundle.getString("resume_menu")); // NOI18N
        optionMenu.add(resumeMenuItem);

        profileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/profile.png"))); // NOI18N
        profileMenu.setText(resourceBundle.getString("profile-list_menu")); // NOI18N

        profilesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/profileBox.png"))); // NOI18N
        profilesMenuItem.setText(resourceBundle.getString("profiles_menu")); // NOI18N
        profileMenu.add(profilesMenuItem);
        profileMenu.add(profileSeparator);

        optionMenu.add(profileMenu);
        optionMenu.add(optionsSeparator);

        refreshAllMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/refreshSeries.png"))); // NOI18N
        refreshAllMenuItem.setText(resourceBundle.getString("refresh-all-series_menu")); // NOI18N
        refreshAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAllActionPerformed(evt);
            }
        });
        optionMenu.add(refreshAllMenuItem);

        refreshCurrentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/refreshAlbums.png"))); // NOI18N
        refreshCurrentMenuItem.setText(resourceBundle.getString("refresh-current-album_menu")); // NOI18N
        refreshCurrentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCurrentAlbumActionPerformed(evt);
            }
        });
        optionMenu.add(refreshCurrentMenuItem);

        toolBar.add(optionMenu);

        languageMenu.setText(resourceBundle.getString("language_menu")); // NOI18N

        languageButtonGroup.add(defaultLanguageCheckBoxMenuItem);
        defaultLanguageCheckBoxMenuItem.setSelected(true);
        defaultLanguageCheckBoxMenuItem.setText(resourceBundle.getString("default-language_menu")); // NOI18N
        defaultLanguageCheckBoxMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/defaultLanguage.png"))); // NOI18N
        languageMenu.add(defaultLanguageCheckBoxMenuItem);
        languageMenu.add(languageSeparator);

        languageButtonGroup.add(englishLanguageCheckBoxMenuItem);
        englishLanguageCheckBoxMenuItem.setText(resourceBundle.getString("english-language_menu")); // NOI18N
        englishLanguageCheckBoxMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/en_US.png"))); // NOI18N
        languageMenu.add(englishLanguageCheckBoxMenuItem);

        languageButtonGroup.add(frenchLanguageCheckBoxMenuItem);
        frenchLanguageCheckBoxMenuItem.setText(resourceBundle.getString("french-language_menu")); // NOI18N
        frenchLanguageCheckBoxMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/fr_FR.png"))); // NOI18N
        languageMenu.add(frenchLanguageCheckBoxMenuItem);

        toolBar.add(languageMenu);

        helpMenu.setText(resourceBundle.getString("help_menu")); // NOI18N

        autoUpdatesCheckBoxMenuItem.setSelected(true);
        autoUpdatesCheckBoxMenuItem.setText(resourceBundle.getString("auto-update_menu")); // NOI18N
        helpMenu.add(autoUpdatesCheckBoxMenuItem);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/mainmenu/aboutIcon.png"))); // NOI18N
        aboutMenuItem.setText(resourceBundle.getString("about_menu")); // NOI18N
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAboutDialog(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        toolBar.add(helpMenu);

        setJMenuBar(toolBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        exit();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void bookFolderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFolderMenuItemActionPerformed
        changeFolder();
    }//GEN-LAST:event_bookFolderMenuItemActionPerformed

    private void refreshAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAllActionPerformed
        listSeries();
    }//GEN-LAST:event_refreshAllActionPerformed

    private void refreshCurrentAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshCurrentAlbumActionPerformed
        int selectedRow = seriesTable.getSelectedRow();
        if (selectedRow != -1) {
            listAlbums(selectedRow);
        }
    }//GEN-LAST:event_refreshCurrentAlbumActionPerformed

    private void closeAboutBox(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAboutBox
        aboutDialog.setVisible(false);
        aboutDialog.dispose();
    }//GEN-LAST:event_closeAboutBox

    private void openAboutDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAboutDialog
        aboutDialog.pack();
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_openAboutDialog

    private void homepageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageLabelMouseClicked
        InetBasics.openURI(appHomepageLabel.getText());
    }//GEN-LAST:event_homepageLabelMouseClicked

    private void albumsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumsTableMouseClicked
        if (evt.getClickCount() == 2 && album != null) {
            startReading();
        }
    }//GEN-LAST:event_albumsTableMouseClicked

    private void previewComponentComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_previewComponentComponentResized
        previewComponent.refresh();
    }//GEN-LAST:event_previewComponentComponentResized

    private void setActionInProgress(boolean inProgress) {
        if (inProgress) {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            //previewComponent.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if (!busyIconTimer.isRunning()) {
                statusAnimationLabel.setIcon(busyIcons[0]);
                busyIconIndex = 0;
                busyIconTimer.start();
            }
        } else {
            this.setCursor(Cursor.getDefaultCursor());
            //previewComponent.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            busyIconTimer.stop();
            statusAnimationLabel.setIcon(idleIcon);
        }
    }
    
    /**
     * Listener sur le changement d'une série
     */
    private synchronized void seriesTableValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (booksDirectory == null) {
            return;
        }
        final int selectedRow = seriesTable.getSelectedRow();
        if (!evt.getValueIsAdjusting() && selectedRow != -1) {
            listAlbums(selectedRow);
        }
    }
    
    /**
     * Modification du dossier contenant les bouquins
     */
    private void changeFolder() {
        booksFolderFileChooser.setCurrentDirectory((booksDirectory == null) ? null : booksDirectory.getParentFile());
        if (booksFolderFileChooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            booksDirectory = booksFolderFileChooser.getSelectedFile();
            // profiles[currentProfile][1] = directory.toString();
            listSeries();
        }
    }
    
    /**
     * Rafraichi la liste de toutes les séries
     */
    private void listSeries() {
        setActionInProgress(true);
        previewComponent.setNoPreviewImage();
        Thread toExecute = new Thread(new Runnable() {

            @Override
            public void run() {
                File[] allfiles = null;
                serie = null;
                album = null;

                try {
                    allfiles = booksDirectory.listFiles();
                } catch(SecurityException ex) {
                    Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                    //new KnownErrorBox(getFrame(), KnownErrorBox.ERROR_LOGO, "Error_Read_Rights", directory.toString());
                }
                if (allfiles == null) {
                    return;
                }
                Arrays.sort(allfiles);
                final File[] allFilesValue = allfiles;
                final DefaultTableModel seriesTableModel = (DefaultTableModel) seriesTable.getModel();
                final DefaultTableModel albumsTableModel = (DefaultTableModel) albumsTable.getModel();
                try {
                    SwingUtilities.invokeAndWait(new Runnable() {

                        @Override
                        public void run() {
                            seriesTableModel.setRowCount(0);
                            albumsTableModel.setRowCount(0);
                        }
                    });
                } catch (InterruptedException | InvocationTargetException ex) {
                    Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                }
                final List<Thread> rows = new ArrayList<>();
                for (int i = 0; allFilesValue.length > i; i++) {
                    if (allFilesValue[i].isDirectory() && !allFilesValue[i].isHidden()) {
                        final int nbrOfAlbums = new File(allFilesValue[i].getPath()).listFiles(new FileFilter() {

                            @Override
                            public boolean accept(File pathname) {
                                String name = pathname.getName();
                                if (!pathname.isHidden() && (pathname.isDirectory() || name.toLowerCase().endsWith(".zip") || name.toLowerCase().endsWith("cbz") || name.toLowerCase().endsWith(".rar") || name.toLowerCase().endsWith(".cbr") || name.toLowerCase().endsWith(".pdf"))) {
                                    return true;
                                }
                                return false;
                            }
                        }).length;
                        final int index = i;
                        Thread tampon = new Thread(new Runnable() {

                            @Override
                            public void run() {
                                seriesTableModel.addRow(new Object[]{allFilesValue[index].getName(), nbrOfAlbums});
                            }
                        });
                        SwingUtilities.invokeLater(tampon);
                        rows.add(tampon);
                    }
                }
                for (Thread thread : rows) {
                    try {
                        thread.join();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                    }
                }
                setActionInProgress(false);
            }
        });
        if (SwingUtilities.isEventDispatchThread()) {
            toExecute.start();
        }
        else {
            toExecute.run();
        }
    }

    @SuppressWarnings("deprecation")
    private void listAlbums(final int selectedRow) {
        setActionInProgress(true);
        new Thread(new Runnable() {

            @Override
            public void run() {
                threadedPreviewLoader.stop();
                serie = null;
                album = null;
                while (threadedPreviewLoader.isAlive() || isAdjusting) {
                    try {
                    Thread.sleep(1);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                    }
                }
                isAdjusting = true;
                serie = new File(booksDirectory.toString() + File.separator + seriesTable.getValueAt(selectedRow, 0).toString());
                File[] allfiles = null;
                try {
                    allfiles = serie.listFiles();
                } catch(SecurityException ex) {
                    Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                    // new KnownErrorBox(getFrame(), KnownErrorBox.ERROR_LOGO, "Error_Read_Rights", serie.toString());
                }
                if (allfiles == null) {
                    previewComponent.setNoPreviewImage();
                    return;
                }
                Arrays.sort(allfiles);
                final File[] allFilesValue = allfiles;
                final DefaultTableModel albumsTableModel = (DefaultTableModel) albumsTable.getModel();
                try {
                    SwingUtilities.invokeAndWait(new Runnable() {

                        @Override
                        public void run() {
                            albumsTableModel.setRowCount(0);
                        }
                    });
                } catch (InterruptedException | InvocationTargetException ex) {
                    Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                }
                List<Thread> rows = new ArrayList<>();
                for (int i = 0; i < allFilesValue.length; i++) {
                    String name = allFilesValue[i].getName();
                    if (!allFilesValue[i].isHidden() && (allFilesValue[i].isDirectory() || name.toLowerCase().endsWith(".zip") || name.toLowerCase().endsWith(".cbz") || name.toLowerCase().endsWith(".rar") || name.toLowerCase().endsWith(".cbr") || name.toLowerCase().endsWith(".pdf"))) {
                        final int index = i;
                        Thread tampon = new Thread(new Runnable() {

                            @Override
                            public void run() {
                                if (allFilesValue[index].isDirectory()) {
                                    albumsTableModel.addRow(new Object[]{allFilesValue[index].getName(), ""});
                                }
                                else {
                                    String albumFullName = allFilesValue[index].getName();
                                    int indexOfExtension = albumFullName.lastIndexOf(".");
                                    albumsTableModel.addRow(new Object[]{albumFullName.substring(0, indexOfExtension), albumFullName.substring(indexOfExtension)});
                                }
                            }
                        });
                        SwingUtilities.invokeLater(tampon);
                        rows.add(tampon);
                    }
                }
                for (Thread thread : rows) {
                    try {
                        thread.join();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                    }
                }
                try {
                    SwingUtilities.invokeAndWait(new Runnable() {

                        @Override
                        public void run() {
                            if (albumsTableModel.getRowCount() != 0) {
                                albumsTable.getSelectionModel().setSelectionInterval(0, 0);
                            }
                            //albumScrollPane.getVerticalScrollBar().setValue(0);
                            isAdjusting = false;
                        }
                    });
                } catch (InterruptedException | InvocationTargetException ex) {
                    Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                }
                setActionInProgress(false);
            }
        }).start();
    }
    
    /**
     * listener sur le changement d'un album (au sein d'une série)
     */
    @SuppressWarnings("deprecation")
    private synchronized void albumsTableValueChanged(javax.swing.event.ListSelectionEvent evt) {
        album = null;
        if (booksDirectory == null) {
            return;
        }
        int selectedRow = albumsTable.getSelectedRow();
        if (!evt.getValueIsAdjusting() && selectedRow != -1) {
            threadedPreviewLoader.stop();
            while (threadedPreviewLoader.isAlive()) {
                try {
                Thread.sleep(1);
                } catch (InterruptedException ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                }
            }
            album = new File(serie.toString() + File.separator + albumsTable.getValueAt(selectedRow, 0).toString() + albumsTable.getValueAt(selectedRow, 1).toString());
            threadedPreviewLoader = new PreviewImageLoader();
            threadedPreviewLoader.start();
        }
    }

    private void startReading() {
        new Thread(new Runnable() {

            @Override
            public void run() {
                if (readInterface != null) {
                    readInterface.setVisible(false);
                    readInterface.dispose();
                }
                readInterface = new ReadInterface(imageHandler);
                readInterface.setVisible(true);
                readInterface.revalidate();
                readInterface.goFirstImage();
            }
        }).start();
    }
    
    private class PreviewImageLoader extends Thread {
        
        public PreviewImageLoader() {
        }

        @Override
        public void run() {
            setActionInProgress(true);
            if (album.isDirectory()) {
                imageHandler = new FolderHandler(album);
                BufferedImage previewImage = imageHandler.getImage(1);
                if (previewImage != null) {
                    previewComponent.setImage(previewImage);
                } else {
                    Logger.getLogger(getClass().getName()).log(Level.SEVERE, "no preview for directory. album : {0}", album);
                }
            }
            else if (album.getName().toLowerCase().endsWith(".zip") || album.getName().toLowerCase().endsWith(".cbz")) {
                imageHandler = new ZipHandler(album);
                BufferedImage previewImage = imageHandler.getImage(1);
                if (previewImage != null) {
                    previewComponent.setImage(previewImage);
                } else {
                    Logger.getLogger(getClass().getName()).log(Level.SEVERE, "no preview for zip. album : {0}", album);
                }
            }
            else if (album.getName().toLowerCase().endsWith(".rar") || album.getName().toLowerCase().endsWith(".cbr")) {
                imageHandler = new RarHandler(album);
                BufferedImage previewImage = imageHandler.getImage(1);
                if (previewImage != null) {
                    previewComponent.setImage(previewImage);
                } else {
                    Logger.getLogger(getClass().getName()).log(Level.SEVERE, "no preview for rar. album : {0}", album);
                }
            }
            else if (album.getName().toLowerCase().endsWith(".pdf")) {
                imageHandler = new PdfHandler(album);
                BufferedImage previewImage = imageHandler.getImage(1);
                if (previewImage != null) {
                    previewComponent.setImage(previewImage);
                } else {
                    Logger.getLogger(getClass().getName()).log(Level.SEVERE, "no preview for pdf. album : {0}", album);
                }
            }
            else {
                previewComponent.setNoPreviewImage();
            }
            setActionInProgress(false);
        }
    }
    
   public void exit() {
       this.setVisible(false);
       this.dispose();
       System.exit(0);
   }
   
   public static Component getPreviewComponent() {
       return previewComponent;
   }

    public ReadInterface getReadInterface() {
        return readInterface;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        preInterface();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainInterface.getInstance().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog aboutDialog;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JScrollPane albumsScrollPane;
    private javax.swing.JTable albumsTable;
    private javax.swing.JLabel appDescLabel;
    private javax.swing.JLabel appHomepageLabel;
    private javax.swing.JLabel appTitleLabel;
    private javax.swing.JLabel appVendorLabel;
    private javax.swing.JLabel appVersionLabel;
    private javax.swing.JCheckBoxMenuItem autoUpdatesCheckBoxMenuItem;
    private javax.swing.JMenuItem bookFolderMenuItem;
    private javax.swing.JFileChooser booksFolderFileChooser;
    private javax.swing.JSplitPane booksPreviewSplitPane;
    private javax.swing.JButton closeAboutDialogButton;
    private javax.swing.JCheckBoxMenuItem defaultLanguageCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem englishLanguageCheckBoxMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JCheckBoxMenuItem frenchLanguageCheckBoxMenuItem;
    private javax.swing.JMenuItem generateReportMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel homepageLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.ButtonGroup languageButtonGroup;
    private javax.swing.JMenu languageMenu;
    private javax.swing.JPopupMenu.Separator languageSeparator;
    private javax.swing.JToolBar mainToolBar;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JPopupMenu.Separator optionsSeparator;
    private static booknaviger.PreviewComponent previewComponent;
    private javax.swing.JLabel productVersionLabel;
    private javax.swing.JComboBox profileComboBox;
    private javax.swing.JMenu profileMenu;
    private javax.swing.JPopupMenu.Separator profileSeparator;
    private javax.swing.JMenuItem profilesMenuItem;
    private javax.swing.JButton refreshAllButton;
    private javax.swing.JMenuItem refreshAllMenuItem;
    private javax.swing.JButton refreshCurrentButton;
    private javax.swing.JMenuItem refreshCurrentMenuItem;
    private javax.swing.JButton resumeButton;
    private javax.swing.JMenuItem resumeMenuItem;
    private javax.swing.JScrollPane seriesScrollPane;
    private javax.swing.JTable seriesTable;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JToolBar statusToolBar;
    private javax.swing.Box.Filler statusToolBarFiller;
    private javax.swing.JMenuBar toolBar;
    private javax.swing.JToolBar.Separator toolbarSeparator1;
    private javax.swing.JToolBar.Separator toolbarSeparator2;
    private javax.swing.JLabel vendorLabel;
    // End of variables declaration//GEN-END:variables
}
