/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package booknaviger.htmlReport;

import org.jdesktop.application.Action;

/**
 *
 * @author Inervo
 */
public class IndexFilePosition extends javax.swing.JDialog {

    private String indexFilePosition = null;

    /**
     * Constructeur de l'IndexFilePosition
     * @param frame Frame parente
     * @param modal modalité de cette fenêtre
     * @param indexFilePosition String indiquant la position du fichier contenant le rapport HTML
     */
    public IndexFilePosition(java.awt.Frame frame, boolean modal, String indexFilePosition) {
        super(frame, modal);
        this.indexFilePosition = indexFilePosition;
        initComponents();
        getRootPane().setDefaultButton(okButton);
        this.setLocationRelativeTo(this.getParent());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        URLTextAreaScrollPane = new javax.swing.JScrollPane();
        URLTextArea = new javax.swing.JTextArea();
        copyButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(booknaviger.BookNavigerApp.class).getContext().getResourceMap(IndexFilePosition.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        LogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLabel.setIcon(resourceMap.getIcon("LogoLabel.icon")); // NOI18N
        LogoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LogoLabel.setName("LogoLabel"); // NOI18N

        infoLabel.setText(resourceMap.getString("infoLabel.text")); // NOI18N
        infoLabel.setName("infoLabel"); // NOI18N

        URLTextAreaScrollPane.setName("URLTextAreaScrollPane"); // NOI18N

        URLTextArea.setEditable(false);
        URLTextArea.setText(indexFilePosition);
        URLTextArea.setMargin(new java.awt.Insets(0, 10, 0, 10));
        URLTextArea.setName("URLTextArea"); // NOI18N
        URLTextAreaScrollPane.setViewportView(URLTextArea);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(booknaviger.BookNavigerApp.class).getContext().getActionMap(IndexFilePosition.class, this);
        copyButton.setAction(actionMap.get("copyURLToClipboard")); // NOI18N
        copyButton.setText(resourceMap.getString("copyButton.text")); // NOI18N
        copyButton.setToolTipText(resourceMap.getString("copyButton.toolTipText")); // NOI18N
        copyButton.setName("copyButton"); // NOI18N

        okButton.setAction(actionMap.get("quit")); // NOI18N
        okButton.setName("okButton"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .add(copyButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(okButton)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(LogoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(infoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
            .add(URLTextAreaScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(infoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(LogoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(URLTextAreaScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(copyButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Executé lors de la sortie de la fenêtre
     */
    @Action
    public void quit() {
        setVisible(false);
        URLTextArea.setText(null);
        dispose();
    }

    /**
     * Copie le contenu de la zone de texte dans le presse-papier
     */
    @Action
    public void copyURLToClipboard() {
        URLTextArea.selectAll();
        URLTextArea.copy();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JTextArea URLTextArea;
    private javax.swing.JScrollPane URLTextAreaScrollPane;
    private javax.swing.JButton copyButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
