/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package booknaviger.htmlReport;

import java.awt.event.KeyEvent;
import org.jdesktop.application.Action;

/**
 *
 * @author Inervo
 */
public class ModeSelector extends javax.swing.JDialog {

    private boolean modeSelected = false;
    private boolean okPressed = false;

    /**
     * Constructeur de la fenêtre de sélection du mode
     * @param frame Frame parente
     * @param modal modalité de la fenêtre
     */
    public ModeSelector(java.awt.Frame frame, boolean modal) {
        super(frame, modal);
        initComponents();
        getRootPane().setDefaultButton(okButton);
        this.setLocationRelativeTo(this.getParent());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeButtonGroup = new javax.swing.ButtonGroup();
        LogoLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        simpleRadioButton = new javax.swing.JRadioButton();
        advancedRadioButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(booknaviger.BookNavigerApp.class).getContext().getResourceMap(ModeSelector.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        LogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLabel.setIcon(resourceMap.getIcon("LogoLabel.icon")); // NOI18N
        LogoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LogoLabel.setName("LogoLabel"); // NOI18N

        infoLabel.setText(resourceMap.getString("infoLabel.text")); // NOI18N
        infoLabel.setName("infoLabel"); // NOI18N

        modeButtonGroup.add(simpleRadioButton);
        simpleRadioButton.setSelected(true);
        simpleRadioButton.setText(resourceMap.getString("simpleRadioButton.text")); // NOI18N
        simpleRadioButton.setName("simpleRadioButton"); // NOI18N
        simpleRadioButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ModeSelector.this.keyPressed(evt);
            }
        });

        modeButtonGroup.add(advancedRadioButton);
        advancedRadioButton.setText(resourceMap.getString("advancedRadioButton.text")); // NOI18N
        advancedRadioButton.setName("advancedRadioButton"); // NOI18N
        advancedRadioButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ModeSelector.this.keyPressed(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(booknaviger.BookNavigerApp.class).getContext().getActionMap(ModeSelector.class, this);
        okButton.setAction(actionMap.get("quit")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ModeSelector.this.keyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .add(okButton)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(LogoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(infoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(advancedRadioButton)
                .addContainerGap(27, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(simpleRadioButton)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(infoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(LogoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(simpleRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(advancedRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            this.dispose();
    }//GEN-LAST:event_keyPressed

    /**
     * Executé lors de la sortie de la fenêtre
     */
    @Action
    public void quit() {
        okPressed = true;
        if (simpleRadioButton.isSelected())
            modeSelected = false;
        else
            modeSelected = true;
        setVisible(false);
        dispose();
    }

    /**
     * Retourne le mode sélectionné
     * @return true si mode simple, false si advanced
     */
    public boolean getModeSelected() {
        return modeSelected;
    }

    /**
     * Retourne si le bouton ok à été pressé
     * @return true si ok à été pressé, false sinon
     */
    public boolean isOkPressed() {
        return okPressed;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JRadioButton advancedRadioButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.ButtonGroup modeButtonGroup;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton simpleRadioButton;
    // End of variables declaration//GEN-END:variables

}
