/*
 */
package booknaviger.inet.htmlreport;

import java.util.ResourceBundle;

/**
 *
 * @author Inervo
 */
public class GenerationProgress extends javax.swing.JDialog {
    
    CreateHTMLReport htmlReport = null;
    ResourceBundle resourceBundle = ResourceBundle.getBundle("booknaviger/resources/GenerationProgress");

    /**
     * Creates new form GenerationProgress
     */
    public GenerationProgress(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this.getParent());
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        actionLabel = new javax.swing.JLabel();
        actionProgressBar = new javax.swing.JProgressBar();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booknaviger/resources/graphics/htmlreport/info.png"))); // NOI18N

        infoLabel.setText(resourceBundle.getString("infoLabelString")); // NOI18N

        cancelButton.setText(resourceBundle.getString("cancelButtonString")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(logoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(infoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(actionLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(actionProgressBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(infoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(logoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(actionLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(actionProgressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cancelButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel() {
        htmlReport.setCancelAsked(true);
        setVisible(false);
        dispose();
    }
    
    /**
     * Set de CreateHTMLReport
     * @param htmlReport Instance de CreateHTMLReport
     */
    public void setHtmlReport(CreateHTMLReport htmlReport) {
        this.htmlReport = htmlReport;
    }

    /**
     * Défini la valeur de la progressBar
     * @param value Nouvelle valeur de la progressBar
     */
    public void setActionProgressBarValue(int value) {
        this.actionProgressBar.setValue(value);
    }

    /**
     * Retourne la valeur de la progressBar
     * @return Valeur de la progressBar
     */
    public int getActionProgressBarValue() {
        return this.actionProgressBar.getValue();
    }

    /**
     * Défini le texte informant de l'action en cours
     * @param value String de l'action en cours
     */
    public void setActionLabelValue(String value) {
        this.actionLabel.setText("<html>" + value + "</html>");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JProgressBar actionProgressBar;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel logoLabel;
    // End of variables declaration//GEN-END:variables
}
